# Generated by Django 5.2.6 on 2025-09-25 08:18

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_conversation_document_message"),
    ]

    operations = [VectorExtension()]
