# Generated by Django 5.2.6 on 2025-09-25 11:55

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_postgres_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('qwen3_embedding_8b', pgvector.django.vector.VectorField(dimensions=4096, help_text='Vector embeddings (qwen3_embedding_8b) of the chunk text')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.document')),
            ],
            options={
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
