# Generated by Django 5.2.6 on 2025-09-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_documentchunk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
