# Generated by Django 5.2.6 on 2025-09-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='end_pos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='start_pos',
            field=models.IntegerField(null=True),
        ),
    ]
