services:
  db:
    image: pgvector/pgvector:pg17-trixie
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
